'use strict';
const CONTACT_API='https://script.google.com/macros/s/AKfycbz6_kf6oXCUycashVMMQ9-hrA73CtopL7xwPsm0DYkE5MxXJyxJrhkdnghIS70_KC641w/exec';
const STAFF_AUTH='https://script.google.com/macros/s/AKfycbypkUc0MqZ07E7pZRglNPeRM56WbCcuWaLpRzi9bVFcPklHDxaaLC7GfzG6ozTGCbEX/exec';
const AUTH_KEY='stepStaffAppAuth',CODE_KEY='stepStaffAppCode',PASSWORD_KEY='stepStaffAppPassword',DRAFT_KEY='stepTeacherLineContactDraftV1';
const $=id=>document.getElementById(id);
let teachers=[],selected=new Set(),sessionToken='',busy=false,imagePayload=null;
async function post(url,data){const response=await fetch(url,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(data),redirect:'follow',cache:'no-store'});if(!response.ok)throw new Error('サーバーに接続できませんでした。');const result=await response.json();if(result.error||result.success===false||result.ok===false)throw new Error(result.error||result.message||'処理できませんでした。');return result}
function storedAuth(){try{return JSON.parse(localStorage.getItem(AUTH_KEY)||'null')}catch{return null}}
function notice(text,type='info'){const el=$('message');el.textContent=text;el.className='notice '+type;el.classList.toggle('hidden',!text)}
async function authenticate(code,password){const result=await post(STAFF_AUTH,{action:'studentQrLogin',code,password});if(!result.sessionToken||!['2','3','4'].includes(String(result.permissionLevel)))throw new Error('利用権限を確認できませんでした。');sessionToken=result.sessionToken;localStorage.setItem(CODE_KEY,String(code));localStorage.setItem(PASSWORD_KEY,String(password));localStorage.setItem(AUTH_KEY,JSON.stringify({code:String(result.loginId||result.code||code),name:result.name||'',permissionLevel:result.permissionLevel,systemPortalSessionToken:sessionToken,systemPortalExpiresAt:result.expiresAt||''}));return result}
async function api(action,extra={}){return post(CONTACT_API,{action,systemPortalSessionToken:sessionToken,...extra})}
async function init(){const draft=localStorage.getItem(DRAFT_KEY)||'';$('body').value=draft;updateMessage();const auth=storedAuth();const code=localStorage.getItem(CODE_KEY)||auth?.code||'';const password=localStorage.getItem(PASSWORD_KEY)||'';$('staffCode').value=code;$('staffPassword').value=password;try{if(auth?.systemPortalSessionToken){sessionToken=auth.systemPortalSessionToken;await loadApp();return}if(code&&password){await authenticate(code,password);await loadApp();return}}catch(e){sessionToken=''}$('loading').classList.add('hidden');$('login').classList.remove('hidden')}
async function loadApp(){const [recipientResult,historyResult]=await Promise.all([api('teacherLineAdminRecipients'),api('teacherLineAdminHistory')]);teachers=Array.isArray(recipientResult.teachers)?recipientResult.teachers:[];renderTeachers();renderHistory(historyResult.history||[]);$('loading').classList.add('hidden');$('login').classList.add('hidden');$('app').classList.remove('hidden')}
function normalizeSearchText(value){return String(value||'').normalize('NFKC').replace(/\s/g,'').toLowerCase()}
function katakanaToHiragana(value){return normalizeSearchText(value).replace(/[ァ-ヶ]/g,char=>String.fromCharCode(char.charCodeAt(0)-0x60))}
function kanaToRomaji(value){
  const pairs={きゃ:'kya',きゅ:'kyu',きょ:'kyo',ぎゃ:'gya',ぎゅ:'gyu',ぎょ:'gyo',しゃ:'sha',しゅ:'shu',しょ:'sho',じゃ:'ja',じゅ:'ju',じょ:'jo',ちゃ:'cha',ちゅ:'chu',ちょ:'cho',ぢゃ:'ja',ぢゅ:'ju',ぢょ:'jo',にゃ:'nya',にゅ:'nyu',にょ:'nyo',ひゃ:'hya',ひゅ:'hyu',ひょ:'hyo',びゃ:'bya',びゅ:'byu',びょ:'byo',ぴゃ:'pya',ぴゅ:'pyu',ぴょ:'pyo',みゃ:'mya',みゅ:'myu',みょ:'myo',りゃ:'rya',りゅ:'ryu',りょ:'ryo',ふぁ:'fa',ふぃ:'fi',ふぇ:'fe',ふぉ:'fo',てぃ:'ti',でぃ:'di',うぃ:'wi',うぇ:'we',うぉ:'wo',ゔぁ:'va',ゔぃ:'vi',ゔ:'vu',ゔぇ:'ve',ゔぉ:'vo'};
  const single={あ:'a',い:'i',う:'u',え:'e',お:'o',か:'ka',き:'ki',く:'ku',け:'ke',こ:'ko',が:'ga',ぎ:'gi',ぐ:'gu',げ:'ge',ご:'go',さ:'sa',し:'shi',す:'su',せ:'se',そ:'so',ざ:'za',じ:'ji',ず:'zu',ぜ:'ze',ぞ:'zo',た:'ta',ち:'chi',つ:'tsu',て:'te',と:'to',だ:'da',ぢ:'ji',づ:'zu',で:'de',ど:'do',な:'na',に:'ni',ぬ:'nu',ね:'ne',の:'no',は:'ha',ひ:'hi',ふ:'fu',へ:'he',ほ:'ho',ば:'ba',び:'bi',ぶ:'bu',べ:'be',ぼ:'bo',ぱ:'pa',ぴ:'pi',ぷ:'pu',ぺ:'pe',ぽ:'po',ま:'ma',み:'mi',む:'mu',め:'me',も:'mo',や:'ya',ゆ:'yu',よ:'yo',ら:'ra',り:'ri',る:'ru',れ:'re',ろ:'ro',わ:'wa',を:'o',ん:'n',ぁ:'a',ぃ:'i',ぅ:'u',ぇ:'e',ぉ:'o',ゃ:'ya',ゅ:'yu',ょ:'yo'};
  const text=katakanaToHiragana(value);let result='',doubleNext=false;
  for(let i=0;i<text.length;i++){const char=text[i];if(char==='っ'){doubleNext=true;continue}if(char==='ー'){const vowel=(result.match(/[aeiou](?!.*[aeiou])/)||[])[0];if(vowel)result+=vowel;continue}const syllable=pairs[text.slice(i,i+2)]||single[char];if(pairs[text.slice(i,i+2)])i++;if(!syllable){result+=char;doubleNext=false;continue}if(doubleNext){result+=(syllable.match(/^[bcdfghjklmnpqrstvwxyz]+/)||[''])[0].charAt(0);doubleNext=false}result+=syllable}
  return result;
}
function searchForms(value){const plain=normalizeSearchText(value),hiragana=katakanaToHiragana(value),romaji=kanaToRomaji(value);return [...new Set([plain,hiragana,romaji].filter(Boolean))]}
function matchesTeacherSearch(query,teacher){if(!normalizeSearchText(query))return true;const queryForms=searchForms(query),targetForms=searchForms(String(teacher.code||'')+String(teacher.name||'')+String(teacher.kana||''));return queryForms.some(q=>targetForms.some(target=>target.includes(q)))}
function filtered(){const q=$('search').value,school=$('school').value;return teachers.filter(t=>(!school||String(t.school||'').includes(school))&&matchesTeacherSearch(q,t))}
function renderTeachers(){const list=$('teacherList'),items=filtered();list.replaceChildren();if(!items.length){const p=document.createElement('p');p.className='help';p.style.padding='12px';p.textContent='該当する登録済み講師はいません。';list.append(p)}for(const t of items){const label=document.createElement('label');label.className='teacher'+(selected.has(String(t.code))?' selected':'');const input=document.createElement('input');input.type='checkbox';input.checked=selected.has(String(t.code));input.addEventListener('change',()=>{input.checked?selected.add(String(t.code)):selected.delete(String(t.code));renderTeachers()});const code=document.createElement('span');code.className='code';code.textContent=t.code;const name=document.createElement('strong');name.textContent=t.name;const school=document.createElement('span');school.className='school';school.textContent=t.school||'';label.append(input,code,name,school);list.append(label)}updateSelection()}
function updateSelection(){const chosen=teachers.filter(t=>selected.has(String(t.code))),list=$('selectedList');$('count').textContent=selected.size+'人選択';$('selectedCount').textContent=selected.size+'人';list.replaceChildren();if(!chosen.length){const empty=document.createElement('span');empty.className='help';empty.textContent='まだ選択されていません。';list.append(empty)}for(const t of chosen){const chip=document.createElement('span');chip.className='selected-chip';const name=document.createElement('strong');name.textContent=t.name+'先生';const remove=document.createElement('button');remove.type='button';remove.title=t.name+'先生の選択を解除';remove.setAttribute('aria-label',remove.title);remove.textContent='×';remove.addEventListener('click',()=>{selected.delete(String(t.code));renderTeachers()});chip.append(name,remove);list.append(chip)}$('openConfirm').disabled=!selected.size||(!$('body').value.trim()&&!imagePayload)}
function updateMessage(){const body=$('body').value;$('chars').textContent=body.length+' / 2000文字';$('preview').textContent=body||(imagePayload?'文章なし（画像のみ送信）':'ここに送信内容が表示されます。');$('previewImageWrap').classList.toggle('hidden',!imagePayload);if(imagePayload)$('previewImage').src=imagePayload.dataUrl;updateSelection()}
function clearImage(){imagePayload=null;$('imageInput').value='';$('imagePreview').removeAttribute('src');$('previewImage').removeAttribute('src');$('confirmImage').removeAttribute('src');$('imageCard').classList.add('hidden');$('previewImageWrap').classList.add('hidden');$('confirmImageWrap').classList.add('hidden');updateMessage()}
function dataUrlBytes(dataUrl){const base64=String(dataUrl||'').split(',')[1]||'';return Math.floor(base64.length*3/4)}
function loadImageFile(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onerror=()=>reject(new Error('画像を読み込めませんでした。'));reader.onload=()=>{const image=new Image();image.onerror=()=>reject(new Error('画像を開けませんでした。JPEGまたはPNGを選んでください。'));image.onload=()=>resolve(image);image.src=String(reader.result)};reader.readAsDataURL(file)})}
async function prepareImage(file){if(!file)return;if(!['image/jpeg','image/png'].includes(file.type))throw new Error('JPEGまたはPNG画像を選んでください。');if(file.size>20*1024*1024)throw new Error('元画像は20MB以下にしてください。');const source=await loadImageFile(file);let width=source.naturalWidth,height=source.naturalHeight;const maxSide=1600;if(Math.max(width,height)>maxSide){const ratio=maxSide/Math.max(width,height);width=Math.round(width*ratio);height=Math.round(height*ratio)}let dataUrl='';for(let attempt=0;attempt<6;attempt++){const canvas=document.createElement('canvas');canvas.width=width;canvas.height=height;const context=canvas.getContext('2d');context.fillStyle='#fff';context.fillRect(0,0,width,height);context.drawImage(source,0,0,width,height);for(const quality of [.9,.82,.74,.66,.58]){dataUrl=canvas.toDataURL('image/jpeg',quality);if(dataUrlBytes(dataUrl)<=850*1024)break}if(dataUrlBytes(dataUrl)<=850*1024)break;width=Math.max(1,Math.round(width*.82));height=Math.max(1,Math.round(height*.82))}if(dataUrlBytes(dataUrl)>900*1024)throw new Error('画像を送信用サイズまで縮小できませんでした。別の画像を選んでください。');imagePayload={dataUrl,name:String(file.name||'image').replace(/[^0-9A-Za-zぁ-んァ-ヶ一-龠._-]/g,'_').replace(/\.(?:jpe?g|png)$/i,'').slice(0,80),bytes:dataUrlBytes(dataUrl)};$('imagePreview').src=dataUrl;$('imageInfo').textContent=imagePayload.name+'（送信用 '+Math.ceil(imagePayload.bytes/1024)+'KB）';$('imageCard').classList.remove('hidden');updateMessage()}
function renderHistory(rows){const body=$('historyBody');body.replaceChildren();if(!rows.length){const tr=document.createElement('tr'),td=document.createElement('td');td.colSpan=6;td.textContent='送信履歴はまだありません。';tr.append(td);body.append(tr);return}for(const row of rows.slice(0,30)){const tr=document.createElement('tr');for(const value of [row.sentAt,row.sender,row.targets,row.count,row.result]){const td=document.createElement('td');td.textContent=String(value??'');tr.append(td)}const td=document.createElement('td'),details=document.createElement('details'),summary=document.createElement('summary'),message=document.createElement('div');details.className='history-details';summary.textContent='送信内容を見る';message.className='history-message';message.textContent=String(row.message||(row.imageUrl?'文章なし（画像のみ送信）':'送信内容の記録がありません。'));details.append(summary,message);if(row.imageUrl){const image=document.createElement('img');image.className='history-image';image.src=String(row.imageUrl);image.alt='送信した画像（保管期限内のみ表示）';image.loading='lazy';details.append(image)}td.append(details);tr.append(td);body.append(tr)}}
$('loginForm').addEventListener('submit',async e=>{e.preventDefault();$('loginMessage').classList.add('hidden');try{await authenticate($('staffCode').value.trim(),$('staffPassword').value);await loadApp()}catch(err){$('loginMessage').textContent=err.message;$('loginMessage').classList.remove('hidden')}});
$('search').addEventListener('input',renderTeachers);$('school').addEventListener('change',renderTeachers);$('body').addEventListener('input',updateMessage);
$('imageInput').addEventListener('change',async e=>{const file=e.target.files?.[0];if(!file){clearImage();return}try{notice('画像を送信用に準備しています。');await prepareImage(file);notice('画像を追加しました。送信前の確認画面でもう一度確認してください。','ok')}catch(err){clearImage();notice(err.message,'error')}});$('removeImage').addEventListener('click',clearImage);
$('selectVisible').addEventListener('click',()=>{filtered().forEach(t=>selected.add(String(t.code)));renderTeachers()});$('clearSelection').addEventListener('click',()=>{selected.clear();renderTeachers()});
$('saveTemplate').addEventListener('click',()=>{localStorage.setItem(DRAFT_KEY,$('body').value);notice('この端末に文章を保存しました。','ok')});
$('openConfirm').addEventListener('click',()=>{const targets=teachers.filter(t=>selected.has(String(t.code)));$('confirmTargets').textContent='送信先：'+targets.map(t=>t.name+'先生').join('、')+'（'+targets.length+'人）';$('confirmBody').textContent=$('body').value.trim()||'文章なし（画像のみ送信）';$('confirmImageWrap').classList.toggle('hidden',!imagePayload);if(imagePayload)$('confirmImage').src=imagePayload.dataUrl;$('confirm').classList.remove('hidden')});
$('cancelSend').addEventListener('click',()=>$('confirm').classList.add('hidden'));
$('send').addEventListener('click',async()=>{if(busy)return;busy=true;$('send').disabled=true;$('send').textContent='送信しています…';try{const text=$('body').value.trim(),hadImage=!!imagePayload;const result=await api('teacherLineAdminSend',{teacherCodes:[...selected],message:text,imageDataUrl:imagePayload?.dataUrl||'',imageName:imagePayload?.name||''});$('confirm').classList.add('hidden');const sentType=hadImage?(text?'文章・画像':'画像'):'文章';notice((result.sentCount||0)+'人へ'+sentType+'を送信しました。'+(result.failedCount?' '+result.failedCount+'人は送信できませんでした。':''),result.failedCount?'error':'ok');selected.clear();clearImage();renderTeachers();const history=await api('teacherLineAdminHistory');renderHistory(history.history||[])}catch(err){notice(err.message,'error');$('confirm').classList.add('hidden')}finally{busy=false;$('send').disabled=false;$('send').textContent='確認して送信する'}});
init();
