'use strict';
const CONTACT_API='https://script.google.com/macros/s/AKfycbz6_kf6oXCUycashVMMQ9-hrA73CtopL7xwPsm0DYkE5MxXJyxJrhkdnghIS70_KC641w/exec';
const STAFF_AUTH='https://script.google.com/macros/s/AKfycbypkUc0MqZ07E7pZRglNPeRM56WbCcuWaLpRzi9bVFcPklHDxaaLC7GfzG6ozTGCbEX/exec';
const AUTH_KEY='stepStaffAppAuth',CODE_KEY='stepStaffAppCode',PASSWORD_KEY='stepStaffAppPassword',DRAFT_KEY='stepTeacherLineContactDraftV1';
const $=id=>document.getElementById(id);
let teachers=[],selected=new Set(),sessionToken='',busy=false;
async function post(url,data){const response=await fetch(url,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(data),redirect:'follow',cache:'no-store'});if(!response.ok)throw new Error('サーバーに接続できませんでした。');const result=await response.json();if(result.error||result.success===false||result.ok===false)throw new Error(result.error||result.message||'処理できませんでした。');return result}
function storedAuth(){try{return JSON.parse(localStorage.getItem(AUTH_KEY)||'null')}catch{return null}}
function notice(text,type='info'){const el=$('message');el.textContent=text;el.className='notice '+type;el.classList.toggle('hidden',!text)}
async function authenticate(code,password){const result=await post(STAFF_AUTH,{action:'studentQrLogin',code,password});if(!result.sessionToken||!['2','3','4'].includes(String(result.permissionLevel)))throw new Error('利用権限を確認できませんでした。');sessionToken=result.sessionToken;localStorage.setItem(CODE_KEY,String(code));localStorage.setItem(PASSWORD_KEY,String(password));localStorage.setItem(AUTH_KEY,JSON.stringify({code:String(result.loginId||result.code||code),name:result.name||'',permissionLevel:result.permissionLevel,systemPortalSessionToken:sessionToken,systemPortalExpiresAt:result.expiresAt||''}));return result}
async function api(action,extra={}){return post(CONTACT_API,{action,systemPortalSessionToken:sessionToken,...extra})}
async function init(){const draft=localStorage.getItem(DRAFT_KEY)||'';$('body').value=draft;updateMessage();const auth=storedAuth();const code=localStorage.getItem(CODE_KEY)||auth?.code||'';const password=localStorage.getItem(PASSWORD_KEY)||'';$('staffCode').value=code;$('staffPassword').value=password;try{if(auth?.systemPortalSessionToken){sessionToken=auth.systemPortalSessionToken;await loadApp();return}if(code&&password){await authenticate(code,password);await loadApp();return}}catch(e){sessionToken=''}$('loading').classList.add('hidden');$('login').classList.remove('hidden')}
async function loadApp(){const [recipientResult,historyResult]=await Promise.all([api('teacherLineAdminRecipients'),api('teacherLineAdminHistory')]);teachers=Array.isArray(recipientResult.teachers)?recipientResult.teachers:[];renderTeachers();renderHistory(historyResult.history||[]);$('loading').classList.add('hidden');$('login').classList.add('hidden');$('app').classList.remove('hidden')}
function filtered(){const q=$('search').value.normalize('NFKC').replace(/\s/g,'').toLowerCase(),school=$('school').value;return teachers.filter(t=>(!school||String(t.school||'').includes(school))&&(!q||(String(t.code)+String(t.name||'')+String(t.kana||'')).normalize('NFKC').replace(/\s/g,'').toLowerCase().includes(q)))}
function renderTeachers(){const list=$('teacherList'),items=filtered();list.replaceChildren();if(!items.length){const p=document.createElement('p');p.className='help';p.style.padding='12px';p.textContent='該当する登録済み講師はいません。';list.append(p)}for(const t of items){const label=document.createElement('label');label.className='teacher';const input=document.createElement('input');input.type='checkbox';input.checked=selected.has(String(t.code));input.addEventListener('change',()=>{input.checked?selected.add(String(t.code)):selected.delete(String(t.code));updateSelection()});const code=document.createElement('span');code.className='code';code.textContent=t.code;const name=document.createElement('strong');name.textContent=t.name;const school=document.createElement('span');school.className='school';school.textContent=t.school||'';label.append(input,code,name,school);list.append(label)}updateSelection()}
function updateSelection(){$('count').textContent=selected.size+'人選択';$('openConfirm').disabled=!selected.size||!$('body').value.trim()}
function updateMessage(){const body=$('body').value;$('chars').textContent=body.length+' / 2000文字';$('preview').textContent=body||'ここに送信内容が表示されます。';updateSelection()}
function renderHistory(rows){const body=$('historyBody');body.replaceChildren();if(!rows.length){const tr=document.createElement('tr'),td=document.createElement('td');td.colSpan=5;td.textContent='送信履歴はまだありません。';tr.append(td);body.append(tr);return}for(const row of rows.slice(0,30)){const tr=document.createElement('tr');for(const value of [row.sentAt,row.sender,row.targets,row.count,row.result]){const td=document.createElement('td');td.textContent=String(value??'');tr.append(td)}body.append(tr)}}
$('loginForm').addEventListener('submit',async e=>{e.preventDefault();$('loginMessage').classList.add('hidden');try{await authenticate($('staffCode').value.trim(),$('staffPassword').value);await loadApp()}catch(err){$('loginMessage').textContent=err.message;$('loginMessage').classList.remove('hidden')}});
$('search').addEventListener('input',renderTeachers);$('school').addEventListener('change',renderTeachers);$('body').addEventListener('input',updateMessage);
$('selectVisible').addEventListener('click',()=>{filtered().forEach(t=>selected.add(String(t.code)));renderTeachers()});$('clearSelection').addEventListener('click',()=>{selected.clear();renderTeachers()});
$('saveTemplate').addEventListener('click',()=>{localStorage.setItem(DRAFT_KEY,$('body').value);notice('この端末に文章を保存しました。','ok')});
$('openConfirm').addEventListener('click',()=>{const targets=teachers.filter(t=>selected.has(String(t.code)));$('confirmTargets').textContent='送信先：'+targets.map(t=>t.name+'先生').join('、')+'（'+targets.length+'人）';$('confirmBody').textContent=$('body').value.trim();$('confirm').classList.remove('hidden')});
$('cancelSend').addEventListener('click',()=>$('confirm').classList.add('hidden'));
$('send').addEventListener('click',async()=>{if(busy)return;busy=true;$('send').disabled=true;$('send').textContent='送信しています…';try{const result=await api('teacherLineAdminSend',{teacherCodes:[...selected],message:$('body').value.trim()});$('confirm').classList.add('hidden');notice((result.sentCount||0)+'人へ送信しました。'+(result.failedCount?' '+result.failedCount+'人は送信できませんでした。':''),result.failedCount?'error':'ok');selected.clear();renderTeachers();const history=await api('teacherLineAdminHistory');renderHistory(history.history||[])}catch(err){notice(err.message,'error');$('confirm').classList.add('hidden')}finally{busy=false;$('send').disabled=false;$('send').textContent='確認して送信する'}});
init();
