import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
const html=readFileSync(new URL('../teacher_line_contact.html',import.meta.url),'utf8');
const js=readFileSync(new URL('../teacher_line_contact.js',import.meta.url),'utf8');
const gas=readFileSync(new URL('../gas/TeacherLineContact.gs',import.meta.url),'utf8');
assert.match(html,/LINE講師連絡システム/);
assert.match(html,/かな／ローマ字/);
assert.match(js,/matchesTeacherSearch/);
const searchable=js.split("$('loginForm')")[0]+`;globalThis.searchFormsForTest=searchForms;globalThis.matchesForTest=matchesTeacherSearch;`;
const sandbox={};
vm.runInNewContext(searchable,sandbox);
assert.equal(sandbox.matchesForTest('おおの',{code:'7002',name:'大野 智子',kana:'オオノ トモコ'}),true);
assert.equal(sandbox.matchesForTest('オオノ',{code:'7002',name:'大野 智子',kana:'おおの ともこ'}),true);
assert.equal(sandbox.matchesForTest('oono',{code:'7002',name:'大野 智子',kana:'オオノ トモコ'}),true);
assert.equal(sandbox.matchesForTest('tomoko',{code:'7002',name:'大野 智子',kana:'オオノ トモコ'}),true);
assert.equal(sandbox.matchesForTest('yamamoto',{code:'7058',name:'山本 花子',kana:'やまもと はなこ'}),true);
assert.equal(sandbox.matchesForTest('sato',{code:'7002',name:'大野 智子',kana:'オオノ トモコ'}),false);
assert.match(html,/確認して送信する/);
assert.match(js,/teacherLineAdminRecipients/);
assert.match(js,/teacherLineAdminSend/);
assert.match(js,/stepStaffAppAuth/);
assert.match(gas,/verifySystemPortal/);
assert.match(gas,/LINE利用者ID/);
assert.match(gas,/LockService/);
assert.doesNotMatch(js,/LINE_CHANNEL_ACCESS_TOKEN\s*=/);
console.log('teacher line contact tests passed');
